version: '3.3'
services:
  web:
    image: "fersol/python-redis:v3"
    ports:
      - "80:5000"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
